apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: SAFMachine
metadata:
  labels:
    app.kubernetes.io/name: saf-api
    app.kubernetes.io/managed-by: kustomize
  name: safmachine-sample
spec:
  provisionJob: 
    spec:
      template:
        spec:
          containers:
            - name: main
              image: ubuntu
              command: 
              - sh 
              - -c 
              - | 
                cat /etc/bootstrap/data
  deprovisionJob: 
    spec:
      template:
        spec:
          containers:
            - name: main
              image: ubuntu
              command: 
              - sh 
              - -c 
              - | 
                cat /etc/bootstrap/data




