apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: SAFMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: saf-api
    app.kubernetes.io/managed-by: kustomize
  name: safmachinetemplate-sample
spec:
  # TODO(user): Add fields here
